#!/bin/bash

# Install Native Messaging Host for Chrome Extension
#
# Chrome launches the host with NO argv — but Clarity only enters native-host mode
# when given --native-host. This script writes a small runner that adds that flag.
#
# Usage:
#   ./install-native-host.sh <extension_id> [path_to_clarity_binary]
#
# Dev example (after `cargo build` or `pnpm dev` once):
#   ./install-native-host.sh abcdefghijklmnop /path/to/oneway/apps/desktop/src-tauri/target/debug/appsdesktop

set -e

EXTENSION_ID="${1:-}"
APP_PATH="${2:-/Applications/Clarity.app/Contents/MacOS/Clarity}"

# Chrome Native Messaging Hosts directory
CHROME_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
CLARITY_CONFIG_DIR="$HOME/.clarity"
RUNNER_PATH="$CLARITY_CONFIG_DIR/clarity-native-host-runner.sh"

# Create directories
mkdir -p "$CHROME_DIR"
mkdir -p "$CLARITY_CONFIG_DIR"

# If no extension ID provided, use a placeholder
if [ -z "$EXTENSION_ID" ]; then
    echo "⚠️  Warning: No extension ID provided."
    echo "   Usage: $0 <extension_id> [app_path]"
    echo ""
    echo "   You can find the extension ID at chrome://extensions"
    echo "   (Enable Developer mode to see the ID)"
    echo ""
    echo "   Using placeholder for now. You'll need to update the manifest later."
    EXTENSION_ID="YOUR_EXTENSION_ID_HERE"
fi

# Resolve to absolute path (required by Chrome manifest)
if [[ "$APP_PATH" != /* ]]; then
    APP_PATH="$(cd "$(dirname "$APP_PATH")" && pwd)/$(basename "$APP_PATH")"
fi

if [ ! -f "$APP_PATH" ] || [ ! -x "$APP_PATH" ]; then
    echo "⚠️  Warning: Binary not found or not executable: $APP_PATH"
    echo "   Build it first (e.g. pnpm dev / cargo build in apps/desktop/src-tauri)."
fi

# Runner script: Chrome invokes this; it must pass --native-host to the real binary.
cat > "$RUNNER_PATH" << EOF
#!/bin/bash
# Auto-generated by install-native-host.sh — do not edit by hand
exec "$APP_PATH" --native-host
EOF
chmod +x "$RUNNER_PATH"

MANIFEST_PATH="$CHROME_DIR/com.clarity.app.json"

# Manifest points at the RUNNER, not the .app binary directly
cat > "$MANIFEST_PATH" << EOF
{
  "name": "com.clarity.app",
  "description": "Clarity Desktop App - Native Messaging Host for Chrome Extension",
  "path": "$RUNNER_PATH",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://$EXTENSION_ID/"
  ]
}
EOF

echo "✅ Native messaging runner installed"
echo "   Runner: $RUNNER_PATH"
echo "   → exec: $APP_PATH --native-host"
echo ""
echo "✅ Manifest installed at:"
echo "   $MANIFEST_PATH"
echo ""
echo "📋 Manifest contents:"
cat "$MANIFEST_PATH"
echo ""
echo ""
echo "🔧 Next steps:"
echo "   1. If you used a placeholder extension ID, re-run: $0 <real_id> <same_binary_path>"
echo "   2. Reload the extension in chrome://extensions"
echo "   3. Heartbeats should appear in ~/.clarity/extension-status.json within ~1 min"
